//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 2.0.0
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class DevTools : EditorWindow
{
    public Button CloseError { get; private set; }

    public Label ErrorMessage { get; private set; }

    public Button CalculateBurstCacheSize { get; private set; }

    public Label labelBurstCacheSize { get; private set; }

    public Button ClearBurstCache { get; private set; }

    public Button RestartBurst { get; private set; }

    public Button NukeScripts { get; private set; }

    public Button NukeLibrary { get; private set; }

    public VisualElement ErrorMessageContainer { get; private set; }

    public void CreateGUI()
    {
        VisualTreeAsset asset = AssetDatabase.LoadAssetAtPath<VisualTreeAsset>("Packages/com.redwyre.devtools/Editor/DevTools.uxml");
        VisualElement ui = asset.CloneTree();
        rootVisualElement.Add(ui);
        CloseError = (Button)rootVisualElement?.Q("CloseError");
        ErrorMessage = (Label)rootVisualElement?.Q("ErrorMessage");
        CalculateBurstCacheSize = (Button)rootVisualElement?.Q("CalculateBurstCacheSize");
        labelBurstCacheSize = (Label)rootVisualElement?.Q("labelBurstCacheSize");
        ClearBurstCache = (Button)rootVisualElement?.Q("ClearBurstCache");
        RestartBurst = (Button)rootVisualElement?.Q("RestartBurst");
        NukeScripts = (Button)rootVisualElement?.Q("NukeScripts");
        NukeLibrary = (Button)rootVisualElement?.Q("NukeLibrary");
        ErrorMessageContainer = (VisualElement)rootVisualElement?.Q("ErrorMessageContainer");
        OnCreateGUI();
    }

    partial void OnCreateGUI();
}